spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

    #    数据库链接池
    hikari:
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 20 # 允许的最大连接数
      auto-commit: true #  连接是否自动提交事务
      idle-timeout: 30000 # 连接池中闲置的最长时间
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000 # 连接在连接池中的最大存活时间
      connection-timeout: 30000 #  获取连接的超时时间
      connection-test-query: SELECT 1 # 执行这个查询来测试连
  security:
    user:
      name: admin # 登录用户名
      password: 123456 # 登录密码
  servlet:
    multipart:
      max-file-size: 10MB # 限制单个上传文件的最大大小为 10MB。如果上传的文件大小超过这个值，将会被拒绝上传。
      max-request-size: 10MB # 限制整个上传请求的最大大小为 10MB。这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝。

#=================================================================
# minio
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: power
  secretKey: 12345678
  bucketName: weblog