spring:
  profiles:
    # 默认激活 dev 环境
    active: dev

jwt:
  # 签发人
  issuer: power
  # 秘钥
  secret: r2DzPTYqI9+4aGBkYH2E1E8/VxXqDOn4FWDj1NiGKWuLGUfvAdB8RpQzNJ2V5jVtxIzJCLF1M00k8IV5bj7ciw==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

#  jackson:
    # 设置后台返参，若字段值为 null, 则不返回
#    default-property-inclusion: non_null
    # 设置日期字段格式
#    date-format: yyyy-MM-dd HH:mm:ss

